- hosts: slave2
  tasks:
          - name: "Configure YUM Repo"
            yum_repository:
                  baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                  name: "Docker"
                  description: "YUM Docker Repository"
                  gpgcheck: no

          - name: "Install containerd.io"
            dnf:
                  name: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.3.7-3.1.el7.x86_64.rpm"
                  state: present
                  disable_gpg_check: yes

          - name: "Install pip and docker-ce"
            package:
                    name:
                            - docker-ce
                            - python3-pip
                    state: present

          - name: "Start and enable docker service"
            service:
                    name: docker
                    state: started

          - name: "Creating directory for webserver"
            file:
                    path: "/root/webserver"
                    state: directory

          - name: "Copying contents of the website"
            copy:
                    src: "/root/ansible/nfshp.html"
                    dest: "/root/webserver"


          - name: "Install Docker SDK for Python"
            pip:
                    name: docker

          - name: "Pulling the docker image"
            docker_image:
                    name: httpd
                    source: pull

          - name: "Disabling SE Linux"
            ansible.posix.selinux:
                    state: disabled

          - name: "Launching the webserver in container"
            docker_container:
                    name: webserver
                    image: httpd
                    volumes: /root/webserver:/usr/local/apache2/htdocs/
                    ports: 81:80
                    state: started

          - name: "Enabling masquerade for public zone"
            ansible.posix.firewalld:
                    masquerade: enabled
                    state: enabled
                    zone: public
                    permanent: true

          - name: "Allowing traffic on port 81"
            ansible.posix.firewalld:
                    zone: public
                    port: 81/tcp
                    state: enabled
                    permanent: true
